app {
  host = "0.0.0.0"
  port = 8080
  jwt-secret = "your-super-secret-key-change-in-production-min-32-chars"
  jwt-expiry-hours = 8
}

database {
  driver = "slick.jdbc.SQLServerProfile$"
  db {
    driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    # ── CHANGE THESE to match your environment ──────────────────────────────
    url      = "jdbc:sqlserver://ACER-NITROV15-F\\SQLEXPRESS:1433;databaseName=SampleDB;encrypt=true;trustServerCertificate=true"
    user     = "sa"
    password = "admin123"
    # ────────────────────────────────────────────────────────────────────────
    numThreads       = 10
    connectionTimeout = 30000
  }
}