package model;

import java.math.BigDecimal;

/**
 * Product - Entity class representing a product in the system
 * 
 * This class models the Products table in the database.
 * Each instance represents one row from the Products table.
 * 
 * Database mapping:
 * - id    → Products.Id    (INT IDENTITY PRIMARY KEY)
 * - name  → Products.Name  (NVARCHAR(100))
 * - price → Products.Price (DECIMAL(10,2))
 * 
 * Note: We use BigDecimal for price instead of double to avoid floating-point
 * precision errors. BigDecimal is the standard for monetary values in Java.
 */
public class Product {
    
    // ================================================================
    // PROPERTIES - match the database columns
    // ================================================================
    
    /**
     * Unique identifier for this product (auto-generated by database)
     */
    private int id;
    
    /**
     * Product name or description
     */
    private String name;
    
    /**
     * Product price (uses BigDecimal for precise decimal handling)
     * Examples: 99.99, 1299.50, 15.00
     */
    private BigDecimal price;
    
    // ================================================================
    // CONSTRUCTORS
    // ================================================================
    
    /**
     * Default constructor - creates an empty Product object
     * Used when you need to create a Product and set properties later
     */
    public Product() {
    }
    
    /**
     * Full constructor - creates a Product with all fields
     * Used when retrieving a product from the database
     * 
     * @param id    The product's unique ID from the database
     * @param name  The product name
     * @param price The product price
     */
    public Product(int id, String name, BigDecimal price) {
        this.id = id;
        this.name = name;
        this.price = price;
    }
    
    /**
     * Partial constructor - creates a Product without an ID
     * Used when inserting a new product (database will auto-generate the ID)
     * 
     * @param name  The new product's name
     * @param price The new product's price
     */
    public Product(String name, BigDecimal price) {
        this.name = name;
        this.price = price;
    }
    
    // ================================================================
    // GETTERS AND SETTERS
    // These allow controlled access to private fields
    // ================================================================
    
    /**
     * Gets the product's ID
     * @return The unique product ID
     */
    public int getId() {
        return id;
    }
    
    /**
     * Sets the product's ID
     * Typically called by DAO when loading from database
     * @param id The unique product ID
     */
    public void setId(int id) {
        this.id = id;
    }
    
    /**
     * Gets the product name
     * @return The product name
     */
    public String getName() {
        return name;
    }
    
    /**
     * Sets the product name
     * @param name The product name
     */
    public void setName(String name) {
        this.name = name;
    }
    
    /**
     * Gets the product price
     * @return The product price as BigDecimal
     */
    public BigDecimal getPrice() {
        return price;
    }
    
    /**
     * Sets the product price
     * @param price The product price as BigDecimal
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    
    /**
     * toString() - Returns a string representation of the Product object
     * Useful for debugging and logging
     * 
     * @return String like "Product{id=1, name='Laptop', price=999.99}"
     */
    @Override
    public String toString() {
        return "Product{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", price=" + price +
                '}';
    }
}