package model;

/**
 * User - Entity class representing a user in the system
 * 
 * This class models the Users table in the database.
 * Each instance represents one row from the Users table.
 * 
 * Database mapping:
 * - id       → Users.Id       (INT IDENTITY PRIMARY KEY)
 * - username → Users.Username (NVARCHAR(50) UNIQUE)
 * - password → Users.Password (NVARCHAR(255))
 */
public class User {
    
    // ================================================================
    // PROPERTIES - match the database columns
    // ================================================================
    
    /**
     * Unique identifier for this user (auto-generated by database)
     */
    private int id;
    
    /**
     * Login username (must be unique across all users)
     */
    private String username;
    
    /**
     * User's password (stored as plain text - in production, use hashing like BCrypt)
     */
    private String password;
    
    // ================================================================
    // CONSTRUCTORS
    // ================================================================
    
    /**
     * Default constructor - creates an empty User object
     * Used when you need to create a User and set properties later
     */
    public User() {
    }
    
    /**
     * Full constructor - creates a User with all fields
     * Used when retrieving a user from the database
     * 
     * @param id       The user's unique ID from the database
     * @param username The user's login name
     * @param password The user's password
     */
    public User(int id, String username, String password) {
        this.id = id;
        this.username = username;
        this.password = password;
    }
    
    /**
     * Partial constructor - creates a User without an ID
     * Used when inserting a new user (database will auto-generate the ID)
     * 
     * @param username The new user's login name
     * @param password The new user's password
     */
    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }
    
    // ================================================================
    // GETTERS AND SETTERS
    // These allow controlled access to private fields
    // ================================================================
    
    /**
     * Gets the user's ID
     * @return The unique user ID
     */
    public int getId() {
        return id;
    }
    
    /**
     * Sets the user's ID
     * Typically called by DAO when loading from database
     * @param id The unique user ID
     */
    public void setId(int id) {
        this.id = id;
    }
    
    /**
     * Gets the username
     * @return The user's login name
     */
    public String getUsername() {
        return username;
    }
    
    /**
     * Sets the username
     * @param username The user's login name
     */
    public void setUsername(String username) {
        this.username = username;
    }
    
    /**
     * Gets the password
     * @return The user's password
     */
    public String getPassword() {
        return password;
    }
    
    /**
     * Sets the password
     * @param password The user's password
     */
    public void setPassword(String password) {
        this.password = password;
    }
    
    /**
     * toString() - Returns a string representation of the User object
     * Useful for debugging and logging
     * Note: Password is intentionally excluded for security
     * 
     * @return String like "User{id=1, username='admin'}"
     */
    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                '}';
    }
}